name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  IMAGE: ${{ secrets.IMAGE }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKERPASS: ${{ secrets.DOCKERPASS }}
  TAG: "latest"

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    
    - name: Debug vars
      run: echo "IMAGE=""$IMAGE" "TAG=""$TAG"

    - name: Build Docker image
      run: sudo docker build --network=host . -t "$IMAGE:$TAG"

    - name: Login to Docker
      run: echo "$DOCKERPASS" | sudo docker login --username "$DOCKER_USER" --password-stdin

    - name: Push image
      run: sudo docker push "$IMAGE:$TAG"
  Deploy:
    runs-on: self-hosted
    steps:
    - name: Deploy
      run: |
        sudo docker pull "$IMAGE:$TAG"
        sudo docker stop myapp || true
        sudo docker rm myapp || true
        sudo docker run -d -p 8089:5000 --name myapp "$IMAGE:$TAG"
