name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  TAG: "latest"

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    
    - name: Debug vars
      run: echo "IMAGE=$IMAGE TAG=$TAG"

    - name: Build Docker image
      run: docker build . -t "$IMAGE:$TAG"

    - name: Login to Docker
      run: echo "$DOCKERPASS" | docker login --username "$DOCKER_USER" --password-stdin

    - name: Push image
      run: docker push "$IMAGE:$TAG"

    - name: Deploy
      run: |
        docker pull "$IMAGE:$TAG"
        docker stop myapp || true
        docker rm myapp || true
        docker run -d -p 80:3000 --name myapp "$IMAGE:$TAG"
